---
# MongoDB Configuration
MONGO_ROOT_PASSWORD: "mongo_root_password"

# S3 Storage (MinIO)
MINIO_ROOT_PASSWORD: "minio_root_password"

# PostgreSQL Configuration
POSTGRES_PASSWORD: "dokploypostgrespassword"