---
- name: Setup SSH
  include_role:
    name: ssh
  vars:
    authorized_key: "{{ ssh_authorized_key }}"
    permit_root_login: "{{ ssh_permit_root_login }}"

- name: Setup fail2ban
  include_role:
    name: fail2ban

- name: Setup UFW
  include_role:
    name: ufw
  vars:
      tcp_ports: "{{ ufw_tcp_ports }}"
      udp_ports: "{{ ufw_udp_ports }}"

- name: Setup iptables for hosting Docker Swarm in Oracle Cloud
  include_role:
    name: iptables

- name: Setup Docker
  include_role:
    name: docker

- name: Finalize firewall setup
  command: echo "Finalizing firewall setup"
  notify:
    - Append FORWARD REJECT rule icmp-host-prohibited
    - Save iptables rules
    - Enable UFW firewall
