---
- hosts: all
  become: true
  gather_facts: true  # Enable fact gathering for all hosts
  roles:
    - oci-swarm-node
  vars:
    ufw_tcp_ports:
      - 22  # SSH
      - 80  # Default HTTP
      - 443  # Default HTTPS
      - 3000  # Next.js Dokploy Server for initial setup
      - 996  # HTTPS connections for a Docker Registry
      - 7946  # Docker Swarm
      - 4789  # Docker Swarm
      - 2377  # Docker Swarm
    ufw_udp_ports:
      - 22  # SSH
      - 7946  # Docker Swarm
      - 4789  # Docker Swarm
      - 2377  # Docker Swarm
    ssh_authorized_key: "{{ lookup('file', '~/.ssh/oci_key.pub') }}"
    ssh_permit_root_login: "yes"

- hosts: manager
  become: true
  roles:
    - swarm_manager
    - dokploy

- hosts: workers
  become: true
  roles:
    - swarm_worker
