---
- hosts: all
  become: true
  gather_facts: true  # Enable fact gathering for all hosts
  roles:
    - oci-swarm-node

- hosts: manager
  become: true
  roles:
    - swarm_manager

- hosts: workers
  become: true
  roles:
    - swarm_worker

- name: Prepare Environment Files
  hosts: manager
  tasks:
    - name: Copy MongoDB init script directory
      copy:
        src: ../docker-stack/templates/mongo/mongodb-init
        dest: /home/ubuntu/

- name: Create Docker Secrets from Control Environment
  hosts: manager
  become: true
  tasks:
    - name: Read secrets.yaml file
      include_vars:
        file: ../docker-stack/templates/mongo/secrets.yaml
        name: secrets

    - name: Check MongoDB password secret
      command: docker secret inspect mongo_root_password
      ignore_errors: yes
      register: secret_check
      changed_when: false
      
    - name: Create MongoDB password secret
      shell: echo -n "{{ secrets.MONGO_ROOT_PASSWORD }}" | docker secret create mongo_root_password -
      when: secret_check.rc != 0

- name: Deploy Application Stack
  hosts: manager
  become: true
  tasks:
    - name: Copy docker-compose file
      copy:
        src: ../docker-stack/templates/mongo/docker-compose.yaml
        dest: /home/ubuntu/docker-compose.yaml

    - name: Deploy stack
      command: "docker stack deploy -c /home/ubuntu/docker-compose.yaml mongo-app"
